[package]
name = "snake"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
bevy.workspace = true
rand.workspace = true

[build-dependencies]
embed-resource.workspace = true
